# https://www.google.com/maps /place/9°03'28.4"N+7°29'42.4"E/
red="\e[1;31m"
green="\e[1;32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
nc="\e[0m"
redbg="\e[41m"
greenbg="\e[42m"
echo -e "${magenta}[*] installing tput... (result in result.txt)"
apt-get install -y ncurses-utils > result.txt
echo -e "${green}[*]=> tput installed successfully"

echo -e "${magenta}[*] installing curl... (result in result.txt)"
apt-get install -y curl > result.txt
echo -e "${green}[*]=> curl installed successfully"

echo -e "${magenta}[*] installing bc... (result in result.txt)"
apt-get install -y bc > result.txt
echo -e "${green}[*]=> bc installed successfully"


center() {
    local text="$1"
    local width=$(tput cols)
    local text_len=${#text}
    local pad=$(( (width - text_len) / 2 ))
    printf "%${pad}s%s%$(( width - text_len - pad ))s\n" "" "$text" ""
}

echo -e "${green}"
center "▄▀█ █▀█ █▀▀ ▀▄▀   ▀█▀ █▀▀ █▀▀ █░█"
center "█▀█ █▀░ ██▄ ▄▀▄   ░█░ ██▄ █▄▄ █▀█"
echo -e "${nc}"
echo -e "${cyan}"
center "[*] Program type : IP checker "
echo -e "${nc}"

echo -e "${red}"
read -p "[*].Enter Target IP : " IP
echo " "
echo "[*] checking ${IP}..."
ipinfo=$(curl -s ipinfo.io/${IP})

ip=$(echo "$ipinfo" | grep -oP '"ip":\s*"\K[^"]+')
country=$(echo "$ipinfo" | grep -oP '"country":\s*"\K[^"]+')
city=$(echo "$ipinfo" | grep -oP '"city":\s*"\K[^"]+')
region=$(echo "$ipinfo" | grep -oP '"region":\s*"\K[^"]+')
#location Google

to_dms() {
    local decimal=$1
    local dir_pos=$2
    local dir_neg=$3

    if (( $(echo "$decimal < 0" | bc -l) )); then
        dir=$dir_neg
        decimal=$(echo "$decimal * -1" | bc -l)
    else
        dir=$dir_pos
    fi

    deg=$(echo "$decimal" | cut -d'.' -f1)
    frac=$(echo "$decimal - $deg" | bc -l)
    min_full=$(echo "$frac * 60" | bc -l)
    min=$(echo "$min_full" | cut -d'.' -f1)
    sec_frac=$(echo "$min_full - $min" | bc -l)
    sec=$(echo "$sec_frac * 60" | bc -l | xargs printf "%.1f")

    echo "${deg}°${min}'${sec}\"${dir}"
}
loc=$(echo "$ipinfo" | grep -oP '"loc":\s*"\K[^"]+')
lat=$(echo "$loc" | cut -d',' -f1)
lon=$(echo "$loc" | cut -d',' -f2)

lat_dms=$(to_dms "$lat" "N" "S")
lon_dms=$(to_dms "$lon" "E" "W")

maps_url="https://www.google.com/maps/place/${lat_dms}+${lon_dms}/"
org=$(echo "$ipinfo" | grep -oP '"org":\s*"\K[^"]+')
timezone=$(echo "$ipinfo" | grep -oP '"timezone":\s*"\K[^"]+')

echo -e "${green}"
width=$(tput cols)
line_width=$(( width * 90 / 100 ))
line=$(printf '%.0s_' $(seq 1 $line_width))
center "$line"
echo ""
center "Retrieved Information :"
echo ""
echo " [*] Target IP : ${IP}"
echo ""
echo " [*] Country : ${country}"
echo ""
echo " [*] City : ${city}"
echo ""
echo " [*] Region : ${region}"
echo ""
echo " [*] Google map url : ${maps_url}"
echo ""
echo " [*] org : ${org}"
echo ""
echo " [*] timezone : ${timezone}"
echo ""
center "$line"
echo -e "${nc}"
echo -e "${red}"
center "this info is generated by https://ipinfo.io/missingauth"
echo -e "${nc}"