
red="\e[1;31m"
green="\e[1;32m"
yellow="\e[33m"
blue="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
nc="\e[0m"
redbg="\e[41m"
greenbg="\e[42m"
echo -e "${magenta}[*] updating packages... (result in result.txt)"
apt-get update -y && apt-get upgrade -y > result.txt
echo -e "${green}[*]=> upgraded successfully"


echo -e "${magenta}[*] installing tput... (result in result.txt)"
apt-get install -y ncurses-utils > result.txt
echo -e "${green}[*]=> tput installed successfully"

echo -e "${magenta}[*] installing curl... (result in result.txt)"
apt-get install -y curl > result.txt
echo -e "${green}[*]=> curl installed successfully"

echo -e "${magenta}[*] installing bc... (result in result.txt)"
apt-get install -y bc > result.txt
echo -e "${green}[*]=> bc installed successfully"


center() {
    local text="$1"
    local width=$(tput cols)
    local text_len=${#text}
    local pad=$(( (width - text_len) / 2 ))
    printf "%${pad}s%s%$(( width - text_len - pad ))s\n" "" "$text" ""
}

echo -e "${green}"
center "▄▀█ █▀█ █▀▀ ▀▄▀   ▀█▀ █▀▀ █▀▀ █░█"
center "█▀█ █▀░ ██▄ ▄▀▄   ░█░ ██▄ █▄▄ █▀█"
echo -e "${nc}"
echo -e "${cyan}"
center "[*] Program type : IP checker "
echo -e "${nc}"

echo -e "${red}"
read -p "[*].Enter Target IP : " IP
echo -e "${nc}"

# --- Validate IP format before making any request ---
ip_regex='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
if [[ -z "$IP" ]]; then
    echo -e "${redbg}[!] No IP entered. Exiting.${nc}"
    exit 1
fi

if [[ ! "$IP" =~ $ip_regex ]]; then
    echo -e "${redbg}[!] '${IP}' is not a valid IP address format. Exiting.${nc}"
    exit 1
fi

# reject any octet over 255 (regex above only checks shape, not range)
valid_octets=true
IFS='.' read -r o1 o2 o3 o4 <<< "$IP"
for octet in "$o1" "$o2" "$o3" "$o4"; do
    if (( octet > 255 )); then
        valid_octets=false
    fi
done
if [[ "$valid_octets" == false ]]; then
    echo -e "${redbg}[!] '${IP}' has an out-of-range octet. Exiting.${nc}"
    exit 1
fi

echo -e "${red}"
echo "[*] checking ${IP}..."
ipinfo=$(curl -s "ipinfo.io/${IP}")

# --- Handle network / empty-response errors ---
if [[ -z "$ipinfo" ]]; then
    echo -e "${redbg}[!] No response from ipinfo.io — check your internet connection. Exiting.${nc}"
    exit 1
fi

# --- Handle ipinfo.io reporting an invalid/unroutable/private IP ---
if echo "$ipinfo" | grep -q '"error"'; then
    err_msg=$(echo "$ipinfo" | grep -oP '"message":\s*"\K[^"]+')
    echo -e "${redbg}[!] ipinfo.io error: ${err_msg:-Invalid IP}${nc}"
    exit 1
fi

if echo "$ipinfo" | grep -q '"bogon":\s*true'; then
    echo -e "${redbg}[!] '${IP}' is a private/reserved (bogon) address with no public location data. Exiting.${nc}"
    exit 1
fi

ip=$(echo "$ipinfo" | grep -oP '"ip":\s*"\K[^"]+')
country=$(echo "$ipinfo" | grep -oP '"country":\s*"\K[^"]+')
city=$(echo "$ipinfo" | grep -oP '"city":\s*"\K[^"]+')
region=$(echo "$ipinfo" | grep -oP '"region":\s*"\K[^"]+')
#location Google

to_dms() {
    local decimal=$1
    local dir_pos=$2
    local dir_neg=$3

    if (( $(echo "$decimal < 0" | bc -l) )); then
        dir=$dir_neg
        decimal=$(echo "$decimal * -1" | bc -l)
    else
        dir=$dir_pos
    fi

    deg=$(echo "$decimal" | cut -d'.' -f1)
    frac=$(echo "$decimal - $deg" | bc -l)
    min_full=$(echo "$frac * 60" | bc -l)
    min=$(echo "$min_full" | cut -d'.' -f1)
    sec_frac=$(echo "$min_full - $min" | bc -l)
    sec=$(echo "$sec_frac * 60" | bc -l | xargs printf "%.1f")

    echo "${deg}°${min}'${sec}\"${dir}"
}
loc=$(echo "$ipinfo" | grep -oP '"loc":\s*"\K[^"]+')

if [[ -z "$loc" ]]; then
    # no coordinates for this IP — skip DMS conversion instead of crashing bc
    maps_url="N/A (no location data for this IP)"
else
    lat=$(echo "$loc" | cut -d',' -f1)
    lon=$(echo "$loc" | cut -d',' -f2)
    lat_dms=$(to_dms "$lat" "N" "S")
    lon_dms=$(to_dms "$lon" "E" "W")
    maps_url="https://www.google.com/maps/place/${lat_dms}+${lon_dms}/"
fi
org=$(echo "$ipinfo" | grep -oP '"org":\s*"\K[^"]+')
timezone=$(echo "$ipinfo" | grep -oP '"timezone":\s*"\K[^"]+')

echo -e "${green}"
width=$(tput cols)
line_width=$(( width * 90 / 100 ))
line=$(printf '%.0s_' $(seq 1 $line_width))
center "$line"
echo ""
center "Retrieved Information :"
echo ""
echo " [*] Target IP : ${IP}"
echo ""
echo " [*] Country : ${country}"
echo ""
echo " [*] City : ${city}"
echo ""
echo " [*] Region : ${region}"
echo ""
echo " [*] Google map url : ${maps_url}"
echo ""
echo " [*] org : ${org}"
echo ""
echo " [*] timezone : ${timezone}"
echo ""
center "$line"
echo -e "${nc}"
echo -e "${red}"
center "this info is generated by https://ipinfo.io/missingauth"
echo -e "${nc}"
